### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by matthijsf** [sdboer78/propresenter-stagedisplay#1]
First of all, LOVE THIS!
Its not really an issue but rather a request. We use multi lingual slides, is there a way to filter out the second language. We use names text boxes, one named English and one names Dutch. They are the layer order with English first.
We'd like to only have English show on the stage display.
Perhaps it's good to mention that when using two separate text boxes in ProPresenter. 
There is no line break in the stage display app. I've attached two screenshot to clarify.
![Screenshot 2019-03-22 at 11 11 20](https://user-images.githubusercontent.com/4282608/54815946-60d53600-4c93-11e9-8982-3bafacdc226f.png)
![Screenshot 2019-03-22 at 11 13 45](https://user-images.githubusercontent.com/4282608/54816086-a8f45880-4c93-11e9-8e50-e36a293584c2.png)

**Comment by sdboer78** [comment]
Hi Matthijs,

Sorry for my late response.
On this moment there is no way to detect another layer in the stagedisplay output.
So thats why we work with a filter character. All lines starting with [ will be filtered out.

So in your example try to use the text:
This is a bunch of english text
Multiple Lines
[ Dit is nederlandse tekst
Ook meerdere regels ]
